// e2e-projects/next-simulator/src/slices/Text/index.tsx
import { Content } from "@prismicio/client";
import { PrismicRichText, SliceComponentProps } from "@prismicio/react";

/**
 * Props for `Text`.
 */
export type TextProps = SliceComponentProps<Content.TextSlice>;

/**
 * Component for "Text" Slices.
 */
export default function Text({ slice }: TextProps): JSX.Element {
  return (
    <section
      data-slice-type={slice.slice_type}
      data-slice-variation={slice.variation}
    >
      <PrismicRichText field={slice.primary.text} />
    </section>
  );
}

// e2e-projects/svelte-kit/src/lib/slices/Text/index.svelte
<script lang="ts">
	import type { Content, SliceZone } from '@prismicio/client';

	export let slice: Content.TextSlice;
	export let slices: SliceZone;
	export let index: number;
	export let context: unknown;
</script>

<section data-slice-type={slice.slice_type} data-slice-variation={slice.variation}>
	Placeholder component for {slice.slice_type} (variation: {slice.variation}) Slices
</section>
